### ISSUE TITLE
Did not run in python 3.6.4 ?

### ISSUE THREAD

**Issue by jebofponderworthy** [dsacre/mididings#26]
I received the following.  Suggestions?

```
Traceback (most recent call last):
  File "./Distribute", line 30, in <module>
    from mididings import *
  File "/usr/lib/python3.6/site-packages/mididings-2015-py3.6-linux-x86_64.egg/mididings/__init__.py", line 13, in <module>
    import _mididings
ImportError: dynamic module does not define module export function (PyInit__mididings)
```

**Comment by markk** [comment]
See here for my fix for this

https://github.com/dsacre/mididings/pull/24/commits/3b2f7d3813a4d43b9ad8f226fb71db2d6538db19

**Comment by jebofponderworthy** [comment]
Put your change in a fork:
https://github.com/ponderworthy/mididings
and clearly it works, thank you.  Do you know why your change didn't show up when I did a 'git clone' of the original?  Clearly I understand very little of the Git and Github environments, though I have read a lot.  Once I have a better understanding of what to do I'll help the Arch people.

**Comment by farvardin** [comment]
This fix should be integrated into the official mididings source!
Thank you, it's working for me now...
